### ISSUE TITLE
pymongo errors when running s3recon

### ISSUE THREAD

**Issue by n0auth** [clarketm/s3recon#3]
I am getting these errors when I run the `s3recon` command. 

```s3recon keywords.txt -o results.json -p
Traceback (most recent call last):
  File "/usr/local/bin/s3recon", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/dist-packages/s3recon/s3recon.py", line 212, in cli
    main(words=words, timeout=timeout, output=output, use_db=db, only_public=public)
  File "/usr/local/lib/python3.7/dist-packages/s3recon/s3recon.py", line 118, in main
    db = MongoDB(host=database["host"], port=database["port"])
  File "/usr/local/lib/python3.7/dist-packages/s3recon/mongodb.py", line 78, in __init__
    self.index(unique_indicies, unique=True)
  File "/usr/local/lib/python3.7/dist-packages/s3recon/mongodb.py", line 86, in index
    self.client[self.db_name][self.col_name].ensure_index(i, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pymongo/collection.py", line 2004, in ensure_index
    self.__create_index(keys, kwargs, session=None)
  File "/usr/local/lib/python3.7/dist-packages/pymongo/collection.py", line 1860, in __create_index
    with self._socket_for_writes() as sock_info:
  File "/usr/local/lib/python3.7/dist-packages/pymongo/collection.py", line 197, in _socket_for_writes
    return self.__database.client._socket_for_writes()
  File "/usr/local/lib/python3.7/dist-packages/pymongo/mongo_client.py", line 1121, in _socket_for_writes
    server = self._get_topology().select_server(writable_server_selector)
  File "/usr/local/lib/python3.7/dist-packages/pymongo/topology.py", line 226, in select_server
    address))
  File "/usr/local/lib/python3.7/dist-packages/pymongo/topology.py", line 184, in select_servers
    selector, server_timeout, address)
  File "/usr/local/lib/python3.7/dist-packages/pymongo/topology.py", line 200, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: 0.0.0.0:27017: [Errno 111] Connection refused
```

**Comment by clarketm** [comment]
It may make sense to fallback to stdout here if MongoDB is unavailable.

@n0auth - Do you have MongoDB running locally on port `27017`? Also, I presume you are invoking with the `--db` flag, correct?

**Comment by n0auth** [comment]
No, I do not. Should I?

**Comment by clarketm** [comment]
Yes, the `--db` flag assumes MongoDB is running - take a look at this [example](https://github.com/clarketm/s3recon#example-2-output-to-a-mongodb-database). Also, if MongoDB is running on a different host or port, then you can configure that using the [`s3recon.yaml`](https://github.com/clarketm/s3recon#q-how-do-i-customize-the-mongodb-host-and-port) file.

**Comment by clarketm** [comment]
@n0auth - did you get that error even without using the `--db` flag? In that case, then this error is not expected. I will create a fix for this and release a patch shortly. Thanks for catching this!

**Comment by clarketm** [comment]
@n0auth - thanks again for the issue! Please check out s3recon [v1.2.2](https://github.com/clarketm/s3recon/tree/v1.2.2) for the fix.

```bash
$ pip install  --upgrade s3recon
```
