### ISSUE TITLE
Docker error

### ISSUE THREAD

**Issue by rishabhdeepsingh** [clarketm/s3recon#4]
While trying to install on Docker I am getting the following error.

```
Collecting s3recon
  Downloading https://files.pythonhosted.org/packages/9c/d4/d762d5b5ece8b91de38a26ef63bc90237cd4c4fd0c48d5f9bcdd89b7fbd1/s3recon-1.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-V5dzlT/s3recon/setup.py", line 11, in <module>
        with open_local(["s3recon", "__init__.py"]) as f:
      File "/tmp/pip-build-V5dzlT/s3recon/setup.py", line 8, in open_local
        return open(path, mode=mode, encoding=encoding)
    TypeError: 'encoding' is an invalid keyword argument for this function

```

**Comment by clarketm** [comment]
@rishabhdeepsingh 
The image you are using likely uses `python 2.x` as the *default* python version. Unfortunately `s3recon` only supports `python 3.6` or greater (https://github.com/clarketm/s3recon/issues/2).

**Comment by rishabhdeepsingh** [comment]
@clarketm  Thanks a lot. Got it working now.
